# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-14 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comdate',
            new_name='cdate',
        ),
    ]
