# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170614_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='media/pics/default.jpeg', upload_to='pics/'),
        ),
    ]
